# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

variables:
  solution: '**/backend/**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK (6.0.100)'
  inputs:
    packageType: sdk
    version: 6.0.100
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: '**/backend/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: '**/backend/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Run UnitTests
  inputs:
    command: 'test'
    projects: '**/backend/**/*.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[System.*]*%2c[xunit.*]*%2c[CSharpWars.Tests.*]*%2c[CSharpWars.DataAccess.*]*'

- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.8.13
    ./reportgenerator "-reports:$(Build.SourcesDirectory)/src/backend/CSharpWars/CSharpWars.Tests/coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)/src/backend/CSharpWars/CSharpWars.Tests/results" "-reporttypes:HTMLInline;HTMLChart" "-assemblyfilters:-CSharpWars.DataAccess.*;-CSharpWars.Tests" "-filefilters:-CSharpWarsDbContextModelSnapshot.cs"

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage results
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)/src/backend/CSharpWars/CSharpWars.Tests/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/src/backend/CSharpWars/CSharpWars.Tests/results
    codecoverageTool: cobertura

- script: |
    dotnet publish ./src/backend/CSharpWars/CSharpWars.Web.Api --configuration "Release" --output ./src/backend/CSharpWars/CSharpWars.Web.Api/bin/Release/publish

- script: |
    dotnet publish ./src/backend/CSharpWars/CSharpWars.Validator --configuration "Release" --output ./src/backend/CSharpWars/CSharpWars.Validator/bin/Release/publish

- script: |
    dotnet publish ./src/backend/CSharpWars/CSharpWars.Web --configuration "Release" --output ./src/backend/CSharpWars/CSharpWars.Web/bin/Release/publish

- script: |
    dotnet publish ./src/backend/CSharpWars/CSharpWars.Processor --configuration "Release" --output ./src/backend/CSharpWars/CSharpWars.Processor/bin/Release/publish

- script: |
    cd ./src/backend/CSharpWars/CSharpWars.Web.Api
    docker build -t djohnnie/csharpwars-api .
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push djohnnie/csharpwars-api

- script: |
    cd ./src/backend/CSharpWars/CSharpWars.Validator
    docker build -t djohnnie/csharpwars-validator .
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push djohnnie/csharpwars-validator

- script: |
    cd ./src/backend/CSharpWars/CSharpWars.Web
    docker build -t djohnnie/csharpwars-web .
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push djohnnie/csharpwars-web

- script: |
    cd ./src/backend/CSharpWars/CSharpWars.Processor
    docker build -t djohnnie/csharpwars-processor .
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push djohnnie/csharpwars-processor
